<?php
return [
    '' => 'site/index',
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => 'v1/auth',
        'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\d+>',
        ],
        'extraPatterns' => [
            'OPTIONS {id}' => 'options',
            'POST login' => 'login',
            'OPTIONS login' => 'options',
            'POST logout' => 'logout',
            'OPTIONS logout' => 'options',
            'POST register' => 'register',
            'OPTIONS register' => 'options',
            'POST forgot' => 'forgot',
            'OPTIONS forgot' => 'options',
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => 'v1/user',
        'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\d+>',
        ],
        'extraPatterns' => [
            'OPTIONS {id}' => 'options',
            'GET profile' => 'profile',
            'POST profile' => 'profile',
            'OPTIONS profile' => 'options',
            'POST account' => 'account',
            'OPTIONS account' => 'options',
            'POST upload-avatar' => 'upload-avatar',
            'OPTIONS upload-avatar' => 'options',
            'GET index' => 'index',
            'OPTIONS index' => 'options',
            'GET update-user' => 'update-user',
            'POST update-user' => 'update-user',
            'OPTIONS update-user' => 'options',
            'DELETE delete-user' => 'delete-user',
            'OPTIONS delete-user' => 'options',
            'GET pt-right' => 'pt-right',
            'OPTIONS pt-right' => 'options',
        ]
    ],
    [
        'class' => 'yii\rest\UrlRule',
        'controller' => 'v1/queue',
        'pluralize' => false,
        'tokens' => [
            '{id}' => '<id:\d+>',
        ],
        'extraPatterns' => [
            'OPTIONS {id}' => 'options',
            'POST register' => 'register',
            'OPTIONS register' => 'options',
            'GET data-print' => 'data-print',
            'OPTIONS data-print' => 'options',
            'GET kiosk-list' => 'kiosk-list',
            'OPTIONS kiosk-list' => 'options',
            'GET departments' => 'departments',
            'OPTIONS departments' => 'options',
            'GET priority' => 'priority',
            'OPTIONS priority' => 'options',
            'GET patient-register' => 'patient-register',
            'OPTIONS patient-register' => 'options',
            'GET dashboard' => 'dashboard',
            'OPTIONS dashboard' => 'options',
            'GET list-all' => 'list-all',
            'OPTIONS list-all' => 'options',
            'DELETE delete' => 'delete',
            'OPTIONS delete' => 'options',
            'POST update-patient' => 'update-patient',
            'OPTIONS update-patient' => 'options',
            'POST data-waiting' => 'data-waiting',
            'OPTIONS data-waiting' => 'options',
            'POST profile-service-options' => 'profile-service-options',
            'OPTIONS profile-service-options' => 'options',
            'POST call-wait' => 'call-wait',
            'OPTIONS call-wait' => 'options',
            'POST data-wait-by-hn' => 'data-wait-by-hn',
            'OPTIONS data-wait-by-hn' => 'options',
            'POST end-wait' => 'end-wait',
            'OPTIONS end-wait' => 'options',
            'POST data-caller' => 'data-caller',
            'OPTIONS data-caller' => 'options',
            'POST recall' => 'recall',
            'OPTIONS recall' => 'options',
            'POST hold' => 'hold',
            'OPTIONS hold' => 'options',
            'POST data-hold' => 'data-hold',
            'OPTIONS data-hold' => 'options',
            'POST end' => 'end',
            'OPTIONS end' => 'options',
            'POST call-hold' => 'call-hold',
            'OPTIONS call-hold' => 'options',
            'POST end-hold' => 'end-hold',
            'OPTIONS end-hold' => 'options',
            'POST call-selected' => 'call-selected',
            'OPTIONS call-selected' => 'options',
        ]
    ],
];